services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kermit
      POSTGRES_PASSWORD: thefrog
      POSTGRES_DB: nce
  mockserver:
    image: mockserver/mockserver
    ports:
      - '8081:1080'
    environment:
      MOCKSERVER_ENABLE_CORS_FOR_ALL_RESPONSES: 'true'
      MOCKSERVER_CORS_ALLOW_ORIGIN: '*'
      MOCKSERVER_WATCH_INITIALIZATION_JSON: 'true'
      MOCKSERVER_INITIALIZATION_JSON_PATH: '/provisioning/*.json'
    volumes:
      - ./compose/provisioning/mockserver:/provisioning
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8082:8080"
    volumes:
      - ./src/main/resources/openapi:/usr/share/nginx/html/api
    environment:
      URLS: |
        [
          {
            "url": "./api/nce-v1.yaml",
            "name": "Naive Currency Exchange (v1)"
          }
        ]